sonar.projectKey=juba-tasklist-frontend
sonar.projectName=juba-tasklist-frontend

sonar.host.url=https://sonarqube.cicd.kits.ext.educentre.fr

sonar.sources=src

sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts,src/__tests__/**/*.e2e.test.ts

sonar.exclusions=\
src/__tests__/**,\
node_modules/**,\
dist/**,\
coverage/**,\
reports/**,\
prisma/migrations/**,\
**/*.config.ts,\
**/*.config.js

sonar.test.exclusions=\
node_modules/**,\
dist/**

sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8

sonar.cpd.exclusions=\
src/__tests__/**